### ISSUE TITLE
Blister Blight

### ISSUE THREAD

**Issue by poonutty** [MonoGame/monogame.github.io#100]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Blister Blight

### Url

https://blisterblight.com/

### Image

![Sludge_Arrow](https://github.com/MonoGame/monogame.github.io/assets/31192611/b611fe6d-9f5a-4a15-bedd-2e5eaa43eda2)

### Logo

![BB_Logo_transparent](https://github.com/MonoGame/monogame.github.io/assets/31192611/4e468c71-e28a-426f-afe0-4fb7b786ad46)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Uploaded
