### ISSUE TITLE
Xon

### ISSUE THREAD

**Issue by Teyken** [MonoGame/monogame.github.io#107]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Xon

### Url

https://store.steampowered.com/app/2400690/Xon/

### Image

![Logo back](https://github.com/MonoGame/monogame.github.io/assets/8403459/a5f929b9-9e1b-4886-b40a-7a7e513425aa)

### Logo

![WebLogo](https://github.com/MonoGame/monogame.github.io/assets/8403459/7fa2c450-d3a3-4f12-9bb3-04e2053a7190)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Thanks for your submission, however, in the future screenshots must be a shot of your game and not just the logo.
