### ISSUE TITLE
WarSphere

### ISSUE THREAD

**Issue by last-tuesday** [MonoGame/monogame.github.io#108]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

WarSphere

### Url

https://store.steampowered.com/app/2451530/WarSphere/

### Image

![screen4_new](https://github.com/MonoGame/monogame.github.io/assets/142100918/4984d919-95a6-43ca-b4c7-1ee6205c96d6)
![screen2_new](https://github.com/MonoGame/monogame.github.io/assets/142100918/874cb8eb-d5c0-4562-ab84-cb07397c2851)
![screenshot_t01](https://github.com/MonoGame/monogame.github.io/assets/142100918/a7b7744a-6c00-41d4-a7b8-46c57dc8f224)

### Logo

![wslogo_1280x720](https://github.com/MonoGame/monogame.github.io/assets/142100918/75ee30a8-61f5-4a7e-b540-c84d07063b7b)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Completed
