### ISSUE TITLE
Getting Started Page Not Found

### ISSUE THREAD

**Issue by des54321** [MonoGame/monogame.github.io#125]
### Link to Document

https://monogame.net/articles/getting_started/index.html

### Description

I'm not sure if this is just an issue for me, but the link to "Getting Started" on the monogame.net website does not load. I'm using firefox and windows 11. Here a screenshot of what happens when I click the "Getting Started" button on the home screen: 
![Screenshot (4)](https://github.com/MonoGame/monogame.github.io/assets/107937531/7e74969d-96d5-4eed-b6c5-fa3c701a9225)

I have tried restarting my computer and my wifi, all other websites work including the rest of the monogame website.

**Comment by Apostolique** [comment]
The correct link should be <https://docs.monogame.net/articles/getting_started/index.html>.

**Comment by des54321** [comment]
Why did the link change, as this wasn't always an issue. Also why would the main monogame website link to the wrong page?
