### ISSUE TITLE
The last war: Forest of doom

### ISSUE THREAD

**Issue by DanielPandaa** [MonoGame/monogame.github.io#127]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

The Last War: Forest of Doom

### Url

https://adc-games.itch.io/the-last-war

### Image

![theLastWar](https://github.com/MonoGame/monogame.github.io/assets/126873452/d2459dea-96ea-41f4-b512-4976bfcd8d07)

### Logo

![iconwar](https://github.com/MonoGame/monogame.github.io/assets/126873452/fa30f7c8-590a-45b0-8d2b-9bdbeeeda023)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [ ] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Completed
