### ISSUE TITLE
 Links in Footer not working (Website)

### ISSUE THREAD

**Issue by Reproog** [MonoGame/monogame.github.io#132]
### Description

Hello,

I have recently discovered C# and the Monogame Framework.

On the [official Monogame Website](https://monogame.net/) I encountered a problem with the links in the footer. Especially with the following links:

- Documentation
- API reference
- About 
- Foundation Statutes

The pages to which these links refer cannot be found or have been moved to other links.

**Comment by SimonDarksideJ** [comment]
@AristurtleDev, can we get these updated asap?
