### ISSUE TITLE
Please consider my indie app, SpinShuffle, for the showcase

### ISSUE THREAD

**Issue by carljohansen** [MonoGame/monogame.github.io#135]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

SpinShuffle

### Url

https://spinshuffle.net

### Image

![Monogame Showcase Screenshot 1080](https://github.com/MonoGame/monogame.github.io/assets/4215173/4a5f0f0c-1ed7-4c6a-b424-86370e59dc2b)

### Logo

![new new icon 340](https://github.com/MonoGame/monogame.github.io/assets/4215173/8f888602-984b-4fbb-83a8-c24fab25e787)

### Tags / Platforms

- [ ] Desktop
- [X] Mobile
- [ ] Console
- [ ] 2D
- [X] 3D
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [X] iOS
- [X] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by carljohansen** [comment]
Sorry; if I understand correctly, I don't think the "icon" that I normally use will be appropriate for your site.  I think that this one might be better:

![icon for monogame showcase](https://github.com/MonoGame/monogame.github.io/assets/4215173/6f0e174d-a162-49ac-b47b-588b2a4851db)

**Comment by SimonDarksideJ** [comment]
Completed
