### ISSUE TITLE
Hard Chip Showcase!

### ISSUE THREAD

**Issue by EtienneLorthoy** [MonoGame/monogame.github.io#141]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Hard Chip

### Url

https://hardchip.io/

### Image

![screenshot1](https://github.com/user-attachments/assets/bff168db-109e-418c-b6a6-1ea13750133d)
![screenshot2](https://github.com/user-attachments/assets/6b4bbf22-f5dd-42c2-b77b-e9420570626b)
![screenshot3](https://github.com/user-attachments/assets/54408f65-1d78-4d5a-a9cc-9dfd989f4c39)
![screenshot4](https://github.com/user-attachments/assets/f3c2b5f2-1be6-4379-88a1-e3ee807a0210)
![screenshot5](https://github.com/user-attachments/assets/1ee323b8-a2cc-4a50-ab6a-557bb6f63e18)

### Logo

![store_capsule_main](https://github.com/user-attachments/assets/2eea34f0-ba64-43cb-98f2-e42ce403fe46)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [ ] 2D
- [X] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Completed

**Comment by EtienneLorthoy** [comment]
Hi @SimonDarksideJ 👋 I wasn't sure at first but it seems since yesterday that a few png files are empty ones (0x0 dimensions)

![image](https://github.com/user-attachments/assets/beec0b08-fb3b-4d8a-85ae-41f09ae71a77)
![image](https://github.com/user-attachments/assets/513dc69b-49d0-4f2b-8b65-6187d18c70e1)

**Comment by SimonDarksideJ** [comment]
Gah, what the. I'll get those images updated asap

**Comment by SimonDarksideJ** [comment]
Fixed, thanks for pointing that out

**Comment by EtienneLorthoy** [comment]
Yes I can see the images now. But it seems a few of us didn't quite gave you the proper assets it seems? Logos seems cropped.

![image](https://github.com/user-attachments/assets/518cd783-c24c-4632-a741-2cf47de82b36)

Here I'm sending you a new version of the logo with transparency and the size asked here https://github.com/MonoGame/monogame.github.io/issues/new?assignees=&labels=showcase&projects=&template=01_Showcase_Submission.yml.

![HardChipInvertedLogo](https://github.com/user-attachments/assets/58b9ab28-a341-4ab5-a963-34064e96b190)

It should work with the look and feel the showcase page is trying to achieve I think.

Thanks!

**Comment by SimonDarksideJ** [comment]
Updated yours, and just spotted the others and resized them too

**Comment by EtienneLorthoy** [comment]
All is good now! Thank you a lot @SimonDarksideJ 🙏! Have a good day
