### ISSUE TITLE
Showcase Submission - Nazdar!

### ISSUE THREAD

**Issue by MichalSkoula** [MonoGame/monogame.github.io#143]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

NAZDAR!

### Url

https://skoula.cz/nazdar/

### Image

![2023-03-04 22_13_40_1920](https://github.com/user-attachments/assets/4c98261d-3ce0-4729-9ac8-ff127f2591da)

### Logo

![logo1](https://github.com/user-attachments/assets/ab3317cd-dc4d-42d1-9c6b-72bc38c726ef)

### Tags / Platforms

- [X] Desktop
- [X] Mobile
- [X] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [X] Linux
- [ ] iOS
- [X] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [X] Xbox One
- [X] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Added to showcase #172
