### ISSUE TITLE
SanGuo

### ISSUE THREAD

**Issue by anonames-lair** [MonoGame/monogame.github.io#150]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

MonoGame

### Url

https://anonames-lair.itch.io/sanguo

### Image

![5battle](https://github.com/user-attachments/assets/fd50c2dd-f3a2-475d-8b5a-55bdc221b8ae)

<div style="color: #ff4500;">
	<strong>Introduction</strong>
</div>
<div>
	Simluation and strategy game based on the Three Kingdoms period in China. Build and manage your forces to conquer and unite the land.<br><br>
	Each playable warlord have their own unique quality and provide different difficulty level.<br><br>
</div>
<div style="color: #ff4500;">
	<strong>How to Play</strong>
</div>
<div>
	The game will start in the strategy phase, where we can manage our forces.<br>
	Click the Play button in the top right corner to proceed the in-game time for 10 days.<br>
	In the 10 days, events like officers finishing their objective and units colliding into a battle can occur.<br>
	After all events concluded, the game will return to the strategy phase.<br><br>
</div>
<div style="color: #ff4500;">
	<strong>Controls</strong>
</div>
<div>
	Playable with a GamePad, or a Mouse (one hand friendly gameplay).<br><br>
	Mouse movement = Game Pad left thumbstick.<br>
	Mouse scroll wheel = Game Pad right thumbstick.<br>
	Mouse left-click = Game Pad A button.<br>
	Mouse right-click = Game Pad B button.<br>
	Keyboard Esc button = Game Pad Back button.<br>
	Keyboard Enter button = Game Pad Start button.<br><br>
</div>
<div>
	<span style="color: #ff4500;"><strong>Best screen resolution:</strong></span> 1080p<br><br>
	<div style="color: #ff4500;"><strong>Minimum system reqs:</strong></div>
	- Intel Core i3 or AMD Ryzen 3<br>
	- 4GB RAM<br>
	- Intel HD Graphics or Radeon HD 7700<br><br>
	<div style="color: #ff4500;"><strong>Recommended system reqs:</strong></div>
	- Intel Core i5 or AMD Ryzen 5<br>
	- 8GB RAM<br>
	- GTX 1050 or Radeon RX 560<br><br>
</div>

### Logo

![Icon](https://github.com/user-attachments/assets/86d0c1dc-a7fa-4439-b238-b4e971846f48)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Added to showcase #172
