### ISSUE TITLE
Mochi Escape

### ISSUE THREAD

**Issue by anonames-lair** [MonoGame/monogame.github.io#174]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Mochi Escape

### Url

https://anonames-lair.itch.io/mochi-escape

### Image

![mochi-gameplay-screenshot](https://github.com/user-attachments/assets/3b65a82d-1ccb-4dd3-b5df-7074d16cd949)

### Logo

![title](https://github.com/user-attachments/assets/38150280-50ff-4c25-9789-1e387f445d19)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [X] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by SimonDarksideJ** [comment]
Added https://github.com/MonoGame/monogame.github.io/commit/c2654d5a35d7b2f6598abc154fac406a0139f45e
