### ISSUE TITLE
Barotrauma showcase submission

### ISSUE THREAD

**Issue by Regalis11** [MonoGame/monogame.github.io#20]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Barotrauma

### Url

https://barotraumagame.com/

### Image

![EN_Press_1080](https://github.com/MonoGame/monogame.github.io/assets/14351070/b7268293-6cbf-4f88-b1c0-04ee67997a10)

**Comment by tomspilman** [comment]
@Regalis11 It would be better to get a game screenshot for the main image.

Also can you provide a game logo no bigger than 340x140 to go with the screenshot?  See the homepage to see how it is used.

**Comment by Regalis11** [comment]
Ah, sorry about that! Here you go, please let me know if you need anything else for the submission:

Screenshot:

![01](https://github.com/MonoGame/monogame.github.io/assets/14351070/bf9bfd32-7003-4942-a29f-c3f2a2cd57f9)

Logo in 340x140 resolution:

![bt_logo](https://github.com/MonoGame/monogame.github.io/assets/14351070/1f1edfd2-cf54-4cd9-ada4-06596c6766c0)

Thank you!

**Comment by tomspilman** [comment]
Done.
