### ISSUE TITLE
Tiny Life showcase submission

### ISSUE THREAD

**Issue by Ellpeck** [MonoGame/monogame.github.io#21]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Tiny Life

### Url

https://tinylifegame.com

### Image

![Banner](https://github.com/MonoGame/monogame.github.io/assets/5741138/5c65b4b0-eee3-45f5-919d-67426513fa6d)

**Comment by tomspilman** [comment]
Hi @Ellpeck 

It would be better fir the screenshot to no have the game logo in it.

Just provide the game logo in a separate image no bigger than 340x140 to go with the screenshot.  See the homepage to see how it is used.

**Comment by Ellpeck** [comment]
Oh, okay! I don't think it specified that in the issue template, but if it did, I must have missed that.

Here you go!

![Banner](https://github.com/MonoGame/monogame.github.io/assets/5741138/229ea9fb-4c36-4ff9-8429-7694aac5748c)

![LogoOriginalSize](https://github.com/MonoGame/monogame.github.io/assets/5741138/7dfa0ab0-604e-4e32-9dcd-8e8a7ebdb6a2)

**Comment by tomspilman** [comment]
> I don't think it specified that in the issue template, but if it did, I must have missed that.

Not your fault... it isn't in the template.  We're fixing that.

**Comment by tomspilman** [comment]
Done.

**Comment by Ellpeck** [comment]
Thanks so much! Unfortunately, it turns out that the size of the logo image I shared is terrible, so here's an updated version that should work better. Also, now that the new issue template is up, additional tags for Tiny Life would be `Linux` and `Mac`. 

Let me know if I should just fix these things myself through a pull request, though!

![TinyLifeLogo](https://github.com/MonoGame/monogame.github.io/assets/5741138/21c4731b-0611-4447-84c2-40f0f168f78d)

**Comment by tomspilman** [comment]
@Ellpeck sure if you want to submit a PR that would be great.
