### ISSUE TITLE
Stay Safe

### ISSUE THREAD

**Issue by gslance** [MonoGame/monogame.github.io#28]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Stay Safe

### Url

https://staysafe.yellowcakegames.com/

### Image

![1-fullhd](https://github.com/MonoGame/monogame.github.io/assets/6259697/352fb391-5695-4a38-b940-0d634a7a0b7d)

### Logo

![transparent logo small](https://github.com/MonoGame/monogame.github.io/assets/6259697/d263f656-14d5-4e8f-ba39-b975a22cb91a)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [X] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [X] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [X] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox
- [ ] PSVita
- [ ] Library

**Comment by tomspilman** [comment]
Done.
