### ISSUE TITLE
PalmRide

### ISSUE THREAD

**Issue by SilviuShader** [MonoGame/monogame.github.io#31]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

PalmRide

### Url

https://www.palmride.online/

### Image

![1920x1080](https://github.com/MonoGame/monogame.github.io/assets/17257658/09bc2730-8e91-4ff6-b8ba-c1edf98d8445)

### Logo

![MonoGameLogo](https://github.com/MonoGame/monogame.github.io/assets/17257658/fd529636-2251-4ddf-944b-33ff5710554f)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [X] 3D
- [X] Windows
- [ ] Mac
- [X] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox
- [ ] PSVita
- [ ] Library

**Comment by tomspilman** [comment]
hey @SilviuShader 

The image should be a screenshot from gameplay ideally.

The logo should be just the title of the game on transparency.

(Not your fault... we're working on making the submission form explain this all better)

**Comment by SilviuShader** [comment]
oh. ok, I just updated the images, thanks for letting me know
