### ISSUE TITLE
Vlad Circus; Descend into Madness

### ISSUE THREAD

**Issue by diegohcanepa** [MonoGame/monogame.github.io#35]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Vlad Circus: Descend into Madness

### Url

https://www.indiesruption.com/games/vlad-circus

### Logo

![image](https://github.com/MonoGame/monogame.github.io/assets/37908473/dc904813-664c-4b47-898d-24a9d9a6d1fb)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [X] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [X] NintendoSwitch
- [X] PlayStation4
- [X] PlayStation5
- [X] Xbox
- [ ] PSVita
- [ ] Library

**Comment by diegohcanepa** [comment]
Hey Tom,
Sure here it goes.

**Comment by tomspilman** [comment]
@diegohcanepa i didn't get anything.  You will need to provide a link or edit the original message.
