### ISSUE TITLE
Randomize Games On Showcase Page

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/monogame.github.io#43]
The showcase page is a little unfair at the moment:

![image](https://github.com/MonoGame/monogame.github.io/assets/103522/0e173df2-7e9a-4ef5-8719-ee5f95529899)

The order they appear on the page is fixed based on the order in the data set.

I propose we fix the showcase page to randomize the game data set before display.

It would be BEST if the randomization is based on a fixed seed of the current date+hour so the order changes hourly.

**Comment by tomspilman** [comment]
@SilviuShader - We will fix this. :)

**Comment by harry-cpp** [comment]
Maybe we should order them by date of release, newest to oldest?

**Comment by tomspilman** [comment]
> Maybe we should order them by date of release, newest to oldest?

Maybe... i considered that or alphabetical order.

Random feels more fair to me and maybe exposes people to old titles at times that they had not seen before.

Like Stardew Valley was released in 2016... seems silly for it being so popular for it to always be at the end of the list.  If this eventually starts to be paginated... do we really want it to always be several pages in?

That was my thinking anyway for a seeded random approach.

**Comment by AristurtleDev** [comment]
@tomspilman This can be closed now. @JakeLegendXIII 's randomization implementation was ported into the 11ty generator as part of #55 so the showcase titles are still now randomized based on the current hour of the day as the seed.
