### ISSUE TITLE
[Discussion] Create A Timeline for the Timeline

### ISSUE THREAD

**Issue by AristurtleDev** [MonoGame/monogame.github.io#45]
The current [About](https://monogame.net/about) page has a timeline that shows the history of the project, which is a simple list of dates with information.  

![image](https://github.com/MonoGame/monogame.github.io/assets/103014489/6eb507e2-9c9b-4d84-972b-706232e37645)

For fun, I experimented with creating a more visual timeline, but not sure if this is a change that would be wanted or not.  Here is what it looks like both on desktop and mobile view ports

**Desktop**
![image](https://github.com/MonoGame/monogame.github.io/assets/103014489/e548240d-762d-4e31-bfc2-5d4a3dc9de40)

**Mobile**
![image](https://github.com/MonoGame/monogame.github.io/assets/103014489/afb3b78a-609d-4dd8-9fb3-4bcdbf9f9ec6)

**Comment by tomspilman** [comment]
I looked at more complex timelines.  By concern is all of them use a ton of space for a single element.  

So i made something MUCH more compact.

I would not mind it being more visually interesting, but not something that takes forever to scroll thru.

**Comment by AristurtleDev** [comment]
> Another thought i had was to encapsulate it into some sort of carrousel of time?

If it was a carousel, would you want it text only information or would you want visuals behind the text? I don't know if yall have any old pics that could be used like when it was discussed at GDC, or anything.

**Comment by AristurtleDev** [comment]
> I like the current timeline, its just missing a line going between all the points 😄

Can add just a line 😆 

This design change was just me playing around a bit last night, it's not something I'm personally hard set on having added. So just opened this as a discussion.

**Comment by tomspilman** [comment]
> If it was a carousel, would you want it text only information or would you want visuals behind the text?

We might have images for a couple things, so we'd have to support both modes if we did it.

An examples out there of what you're thinking of?

**Comment by AristurtleDev** [comment]
Self closing this, timeline was implemented in #55
