### ISSUE TITLE
Petition to use a full width layout for the API docs

### ISSUE THREAD

**Issue by Apostolique** [MonoGame/monogame.github.io#46]
### Link to Document

https://github.com/MonoGame/monogame.github.io/blob/bee262945520857b217edda47d57d6178114d005/templates/monogame/layout/_master.tmpl#L111

### Description

I think we should replace `container-xxl` for `container-fluid` in the API pages. Having a full width layout would make the page breathe better.

![image](https://github.com/MonoGame/monogame.github.io/assets/2766423/cd562870-6d8b-4f57-873f-f344fe10e5cd)
would become:
![image](https://github.com/MonoGame/monogame.github.io/assets/2766423/02392a69-633b-4640-b122-8ba49b7d537f)

**Comment by tomspilman** [comment]
@AristurtleDev thoughts?

I do feel at times the page is too narrow.

But also i hate it when site stretches too much... like when you fullscreen it on a big widescreen monitor.

So not sure.

**Comment by AristurtleDev** [comment]
@tomspilman It depends on the page being displayed really.  For documentation pages, I think it feels better to fill as much space as possible to making the reading easier.  It helps the text seem less dense and more manageable to read through.  For other pages, like the landing page, about section, showcase, pretty much any non-documentation page, centering in the content with margins helps to focus the visual content and elements being presented. Especially with the way we as humans tend to scan the screen to find information or things to interact with on the page.

The average resolution in 2023 is still 1920x1080, which means the `*-xxl` breakpoint in bootstrap would be hit for the majority of people (`≥1400px` https://getbootstrap.com/docs/5.3/layout/breakpoints/#available-breakpoints).  On monitors like mine at home, it's not that narrow, but my monitor in my office (3840 x 2160) it's very narrow. But this isn't a resolution the average user is hitting right now.

I think it would be fine to split having the API pages only us `container-fluid` for full width and the non-documentation pages use `container-xxl`.

(also while I'm here, I would suggest a good book to read if you are interested, it's not very long, called [Don't Make Me Think: A Common Sense Approach to Web Usability](https://www.amazon.com/Dont-Make-Me-Think-Usability/dp/0321344758).  But web design is always boring lol so no offense if you dismiss and never read it.)

**Comment by Apostolique** [comment]
I agree that fluid can stretch too much. Looks like `container` is a more appropriate class for this. It will also be more inline with the Microsoft docs site. [snip](https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder).
