### ISSUE TITLE
Yuppie Psycho

### ISSUE THREAD

**Issue by monsieurmax** [MonoGame/monogame.github.io#52]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Yuppie Psycho

### Url

https://baroquedecay.com/#games

### Image

![captura_02](https://github.com/MonoGame/monogame.github.io/assets/6823880/948868e0-fc90-49fc-ab24-8d686caebe64)

### Logo

![yuppie_psycho_512x512_transparent_simple](https://github.com/MonoGame/monogame.github.io/assets/6823880/8851bc3a-5382-47a7-8f33-1d8a160b79f6)

### Tags / Platforms

- [X] Desktop
- [X] Mobile
- [X] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [X] Mac
- [X] Linux
- [X] iOS
- [X] Android
- [ ] WindowsPhone
- [X] NintendoSwitch
- [X] PlayStation4
- [ ] PlayStation5
- [X] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by AristurtleDev** [comment]
@monsieurmax 
This PR was pushed through but the conversation came up about having a different screenshot to use.  I just wanted to bring it to your attention if you have a different one that can be used for the showcase page.

See here for reference: https://github.com/MonoGame/monogame.github.io/pull/96#issuecomment-1950283796

**Comment by monsieurmax** [comment]
![ss_3e5c3e0d271aa352a6e32ad926415dbbf803aef4](https://github.com/MonoGame/monogame.github.io/assets/6823880/cc7944b0-b518-4caa-b04a-22558c354d84)
Here's a new one, with no gore
