### ISSUE TITLE
Main class view only accessible from sub-pages.

### ISSUE THREAD

**Issue by KelsamGames** [MonoGame/monogame.github.io#84]
### Description

It seems the navigation only opens sub-pages now so the only way to get to the parent page (i.e. https://monogame.net/api/Microsoft.Xna.Framework.Input/) is by navigating to one of those first and then clicking on the parent in the breadcrumb at the top of the page. Perhaps it'd be better to have JS only listen to clicks on the little arrow to expand/collapse the child links and have a click on the actual label open the primary class's page.

**Comment by AristurtleDev** [comment]
This is now resolved through #94 and can be closed.
