### ISSUE TITLE
Showcase Submission - Melkhior's Mansion

### ISSUE THREAD

**Issue by BitGlint** [MonoGame/monogame.github.io#88]
### Prerequisites

- [X] This game/tool/library is my own work
- [X] This game/tool/library has shipped and is available for users.

### Type

Game

### Name

Melkhior's Mansion

### Url

https://bitglint.itch.io/melkhiors-mansion

### Image

![mmscreen1920](https://github.com/MonoGame/monogame.github.io/assets/82390390/2eee4e52-c824-4396-aca8-61b930861854)

### Logo

![Logo](https://github.com/MonoGame/monogame.github.io/assets/82390390/955530bf-8e16-4d5f-aea7-81e8493a8b53)

### Tags / Platforms

- [X] Desktop
- [ ] Mobile
- [ ] Console
- [X] 2D
- [ ] 3D
- [X] Windows
- [X] Mac
- [X] Linux
- [ ] iOS
- [ ] Android
- [ ] WindowsPhone
- [ ] NintendoSwitch
- [ ] PlayStation4
- [ ] PlayStation5
- [ ] Xbox One
- [ ] Xbox Series X/S
- [ ] PSVita
- [ ] Library

**Comment by mrhelmut** [comment]
Didn't know it was made with MonoGame! I really liked it and dig the ZX look.
